### PR TITLE
Inherit from `requests.Session`

### LINKED ISSUE #2: [FEATURE] The Pendo client should inherit from `requests.Session`
### Is your feature request related to a problem

Currently, the client just uses `requests` methods, rather than a proper session. This should inherit from `requests.Session` to give the client all of the power that a proper session has to offer. For example, if one were to add another endpoint to the client, a large amount of code would be repeated. All of the request handling logic should be deferred to the Session, only adding bits where necessary to avoid repeating code.

### The solution you would like

Inherit from `requests.Session` and move most request handling code to `Pendo.request`

### PR DESCRIPTION
**Pull request by samamorgan**
* [x] I have added tests to `tests` to cover my changes.
* [ ] I have added `docs/`, if necessary.
* [ ] I have updated the `README.md`, if necessary.
* [ ] I have updated the `CONTRIBUTING.md`, if necessary.

## What issue does this pull request close?

Closes #2

## How are these changes tested?

The existing tests were refactored to use `pytest.monkeypatch` fixtures to mock requests rather than `unittest.mock`, which is more appropriate for projects that primarily use `pytest`.

## Changelog
The primary purpose of this PR is to make this library far more extensible and more in-line with the Requests library. With these changes, adding additional endpoint methods to the client should be very straightforward and DRY.

- Pendo client now inherits from `requests.Session`
- Added an auth handler class to add required auth headers
- Base URL optionally passed to client constructor
- Request handling moved to `Pendo.request`
  - This centralizes all request logic and makes this library far more extensible
  - Handles URL compilation
  - Requests now try to resolve the json payload, passing resolved data to `PendoRequest`
  - Headers automatically handled by the underlying `Session` (`Content-Type`, `charset`)
- Added `data` attribute to `Request` type
- Use `HTTPStatus` for status code validation
- Replaced all instances of `unittest.Mock` with `pytest.monkeypatch` fixtures
- Added a test to ensure live API calls are blocked

### CODE REVIEW

**Review by setu4993 — COMMENTED** [review]
Thanks for your contribution, @samamorgan. This looks great. The tests are failing because of missing type annotations.

If you can get that fixed, happy to get this released soon.

**Comment by samamorgan** [comment]
> Thanks for your contribution, @samamorgan. This looks great. The tests are failing because of missing type annotations.
> 
> If you can get that fixed, happy to get this released soon.

Thanks for approving the workflows!

I've fixed the various typing issues. Some I intentionally ignored in-line as they were silly to try and fix. I also updated some docstrings to more accurately reflect the structure.

**Review by setu4993 — APPROVED** [review]
Thanks again! A good set of changes. I have a few suggestions / nitpicks but I can make those in a follow-up after getting this out.

**Comment by setu4993** [comment]
@samamorgan : Actually, can you [sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

**Comment by samamorgan** [comment]
> Thanks again! A good set of changes. I have a few suggestions / nitpicks but I can make those in a follow-up after getting this out.

No problem! I'd love to see your feedback, especially around typing if you see any issues there. Typing has evolved a lot lately and I'm admittedly behind the curve.

**Comment by samamorgan** [comment]
> @samamorgan : Actually, can you [sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

Odd, I must have my got client configured improperly. Will fix shortly.

**Comment by samamorgan** [comment]
@setu4993 Squashed my commits under a new signed commit.

**Review by setu4993 — APPROVED** [review]

**Comment by setu4993** [comment]
> > Thanks again! A good set of changes. I have a few suggestions / nitpicks but I can make those in a follow-up after getting this out.
> 
> No problem! I'd love to see your feedback, especially around typing if you see any issues there. Typing has evolved a lot lately and I'm admittedly behind the curve.

Sure thing. I can tag you in a follow-up PR once I get around to it :).

**Comment by setu4993** [comment]
@samamorgan : v0.0.5 of this package is [published to PyPI](https://pypi.org/project/pendo/).

**Pull request merged**
